CONTIKI_PROJECT = node
all: $(CONTIKI_PROJECT)

CONTIKI=../../..
CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

CONTIKI_WITH_IPV6 = 1
MAKE_WITH_ORCHESTRA ?= 0 # force Orchestra from command line
MAKE_WITH_STATIC_SCHEDULER ?= 0 # force static-scheduler from command line
MAKE_WITH_SECURITY ?= 0 # force Security from command line

#APPS_START
#APPS_END

#MODULES_START
#MODULES_END

#CFLAGS_START
#CFLAGS_END


include $(CONTIKI)/Makefile.include
