#ifndef __STATIC_SCHEDULER_GENERATED_H__
#define __STATIC_SCHEDULER_GENERATED_H__

#include "net/mac/tsch/tsch-conf.h" /* for TSCH_WITH_OVERHEARING */
#include "net/mac/tsch/tsch-queue.h" /* for TSCH_MAC_MAX_FRAME_RETRIES */


#define STATIC_SCHEDULER_CHANNEL_COUNT 1
#define STATIC_SCHEDULER_TIMESLOT_COUNT 357
#define STATIC_SCHEDULER_CELL_ENTRIES 6
#define STATIC_SCHEDULER_L3_PACKET_TRANSMISSIONS_COUNT 1


#endif /* __STATIC_SCHEDULER_GENERATED_H__ */
